branch-defaults:
  dev:
    environment: Cloudserverapplication-env-1
  main:
    environment: Cloudserverapplication-env-1
environment-defaults:
  Cloudserverapplication-env-1:
    branch: null
    repository: null
global:
  application_name: cloud-serverApplication
  branch: dev
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: cloud-Servers
  sc: git
  workspace_type: Application
